#!/bin/bash
termux-setup-storage
apt install python ffmpeg termux-api&& pip install youtube-dl
chmod +x ~/bin/termux-url-opener && echo "Termux share button activated"
chmod +x ~/.shortcuts/update && echo "Termux widget shortcut added"
